### PR TITLE
Throw error for writing /taken before /with

### LINKED ISSUE #295: [UG] Indicate in filter that `/taken` must be indicated right after `/with`

### PR DESCRIPTION
**Pull request by Eola-Z**
Fixes #295

### CODE REVIEW

**Comment by nknguyenhc** [comment]
I don't think there is any misleading bug to catch here, this may be counted as feature change, we should indicate the current behaviour in UG instead.

**Comment by Eola-Z** [comment]
It's currently throwing the wrong error message though; it's showing "can only filter by ..." if you type "filter /by course /taken true /with a b c"

**Comment by nknguyenhc** [comment]
I still feel that this might constitute a feature change, better clarify this on the forum.
My suggestion is just to specify the current behaviour in UG.

**Comment by Eola-Z** [comment]
Ok, created a question in the forum

**Comment by Eola-Z** [comment]
Got the ok from Prof:

image

[Link to question](https://github.com/nus-cs2103-AY2324S1/forum/issues/448#issuecomment-1807977285)

**Review by nknguyenhc — APPROVED** [review]
Alright, LGTM!

**Pull request merged**
