### PR TITLE
Fix log file readonly bug

### LINKED ISSUE #236: NullPointerException when app has no write permission to log file

### PR DESCRIPTION
**Pull request by nknguyenhc**
If log file does not have write permission, create a new log file with a different name.

### CODE REVIEW

**Comment by nknguyenhc** [comment]
Update: logger now ignores the lack of write permission, and simply moves on.

**Review by Singa-pirate — COMMENTED** [review]
image

Tested on linux and everything works fine, except uncaught exception when creating user pref file without write access to directory.

**Comment by nknguyenhc** [comment]
That is logger logging out the error message, not an actual runtime exception. Line 196 in `MainApp.java`.

**Comment by Singa-pirate** [comment]
> That is logger logging out the error message, not an actual runtime exception. Line 196 in `MainApp.java`.

Okay, the rest LGTM.

**Review by Singa-pirate — APPROVED** [review]

**Pull request merged**
